name: example
description: Riverpod tachyon plugin example
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.1.3

dependencies:
  riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.21.0
  tachyon: ^0.2.0
  riverpod_tachyon_plugin:
    path: ..