name: riverpod_tachyon_plugin
description: Riverpod code generator using Tachyon.
version: 0.0.1-dev.2

homepage: https://github.com/spideythewebhead/riverpod_tachyon_plugin
repository: https://github.com/spideythewebhead/riverpod_tachyon_plugin
documentation: https://github.com/spideythewebhead/riverpod_tachyon_plugin
issue_tracker: https://github.com/spideythewebhead/riverpod_tachyon_plugin/issues

environment:
  sdk: ^3.1.0

dependencies:
  crypto: ^3.0.3
  tachyon: ^0.3.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.7
